triggers:
- name: backfill_token_transfer
  schedule_type: time
  schedule_interval: "@once"
  start_time: 2023-05-01
  status: inactive
  variables: {'start_date': '2023-05-01', 'end_date': '2023-05-7'}
